version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studymate-app-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/studymate
      - SPRING_DATASOURCE_USERNAME=studymate
      - SPRING_DATASOURCE_PASSWORD=studymate123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=redis123
      - JWT_SECRET_KEY=dev-jwt-secret-key-change-in-production
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - studymate-network

  db:
    image: mysql:8.0
    container_name: studymate-mysql-dev
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=studymate
      - MYSQL_USER=studymate
      - MYSQL_PASSWORD=studymate123
      - TZ=Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - studymate-network

  redis:
    image: redis:7-alpine
    container_name: studymate-redis-dev
    command: redis-server --requirepass redis123 --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - studymate-network

volumes:
  mysql-data:
  redis-data:

networks:
  studymate-network:
    driver: bridge