version: '3.9'

services:
  app:
    image: ${REGISTRY_URL}/${IMAGE_NAME}:latest
    container_name: studymate-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure:5
    environment:
      # Spring Boot Profile
      - SPRING_PROFILES_ACTIVE=prod
      # Database Configuration (MySQL) - 하드코딩
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/studymate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&maxReconnects=10&initialTimeout=15
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=studymate
      - SPRING_DATASOURCE_PASSWORD=studymate123!
      # HikariCP Connection Pool Settings
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=120000
      - SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT=5000
      - SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD=60000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      # JPA Configuration
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=true
      - JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # OAuth Configuration - 하드코딩
      - NAVER_CLIENT_ID=EzXpYAkIVhX1ViFQ5edo
      - NAVER_CLIENT_SECRET=Zml5tphcOJ
      - NAVER_REDIRECT_URI=https://api.languagemate.kr/login/oauth2/code/naver
      - GOOGLE_CLIENT_ID=1068056726433-kf4s0t3jj6iis0aep2kvtgfcebfmfquj.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=https://api.languagemate.kr/login/oauth2/code/google
      # JWT Configuration - 하드코딩
      - JWT_SECRET=c3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRlc3R1ZHltYXRl
      - JWT_ACCESS_TOKEN_EXPIRATION=3600000
      - JWT_REFRESH_TOKEN_EXPIRATION=604800000
      # NCP Object Storage - 하드코딩
      - NCP_REGION=kr-standard
      - NCP_OBJECT_STORAGE_ENDPOINT=https://kr.object.ncloudstorage.com
      - NCP_ACCESS_KEY=ncp_iam_BPAMKR1FHfq8OtlptO2s
      - NCP_SECRET_KEY=ncp_iam_BPKMKRIVHA3Sg1Rd0nLEMJLBS3mLodofDT
      - NCP_BUCKET_NAME=languagemate-profile-img
      # Clova Studio API - 하드코딩
      - CLOVA_STUDIO_ENDPOINT=https://clovastudio.stream.ntruss.com
      - CLOVA_API_KEY=nv-4ca906c1bf814a59a0fd629d0beec6aaH11S
      # Timezone
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: mysql:8.0
    container_name: studymate-mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=studymate123!
      - MYSQL_DATABASE=studymate
      - MYSQL_USER=studymate
      - MYSQL_PASSWORD=studymate123!
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=1G
      --max-connections=200
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long_query_time=2
    restart: unless-stopped
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pstudymate123!", "-e", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: studymate-redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 데이터베이스 백업 서비스 (임시 비활성화 - 별도 구성 필요)
  # db-backup:
  #   image: mysql:8.0
  #   container_name: studymate-backup
  #   depends_on:
  #     - db
  #   environment:
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=studymate
  #     - BACKUP_RETENTION_DAYS=7
  #   volumes:
  #     - ./backups:/backups
  #     - ./scripts/backup.sh:/backup.sh:ro
  #   command: >
  #     sh -c "
  #     apt-get update &&
  #     apt-get install -y cron &&
  #     echo '0 2 * * * /backup.sh' | crontab - &&
  #     cron -f
  #     "
  #   restart: unless-stopped
  #   networks:
  #     - studymate-network

  # 모니터링 (선택사항)
  watchtower:
    image: containrrr/watchtower
    container_name: studymate-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  studymate-network:
    driver: bridge
    name: studymate-network
    ipam:
      config:
        - subnet: 172.20.0.0/16